### ISSUE TITLE
Voice-Sperre modular machen

### ISSUE THREAD

**Issue by Lou-M** [FU-Hagen-Discord/fernuni-bot#105]
Aktuell schließt `!voice <switch>` alle Sprachchannels gleichzeitig.
Gut wäre die Möglichkeit, aussuchen zu können, welche Sprachchannels geschlossen werden sollen.
(Vorschlag von Sunflower)

**Comment by ffaadd** [comment]
Was ist der Vorteil? 
Die Intention des Kommandos ist, dass man den Austausch der Nutzer während der Klausuren unterbindet.
