### ISSUE TITLE
Mehr Bestätigungen

### ISSUE THREAD

**Issue by dnns01** [FU-Hagen-Discord/fernuni-bot#11]
Aktuell bestätigen einige Commands nicht, dass es erfolgreich war.

**Comment by L-MzK** [comment]
Wenn bei einem Text-Kommando `!beispiel` keine Texte hinterlegt sind, passiert gar nichts, wenn man versucht die Liste über `!texts !beispiel` aufzurufen.

**Comment by ffaadd** [comment]
- Wenn der letzte Text mit `!remove-text !command <index>` gelöscht wird, wird auch das Text-Kommando selbst gelöscht. Das teilt Boty dem Aufrufer aber nicht mit.

**Comment by Lou-M** [comment]
- [ ] Eine Bestätigung bei ~~`!request-group`~~ *inzw. `!lg request`* (in dem Channel, wo die Anfrage gemacht wurde), die auf #channel-wünsche verweist, wäre ganz gut.
- [ ] Es kommt auch keine Bestätigung, wenn ein Mod das Command ~~`!add-group`~~`!lg add` verwendet.

**Comment by L-MzK** [comment]
- [ ] Es fehlt eine Bestätigung, wenn ein Vorschlag über `!poll suggest` eingereicht wird.

**Comment by L-MzK** [comment]
- [ ] `!commands remove` wird nicht bestätigt.

**Comment by Lou-M** [comment]
@dnns01 ich meine, dass dieses Issue hier eigentlich zu breit gefasst ist, um konkret gelöst zu werden und inhaltlich mehrere andere Issues umfasst: wäre mehr ein GitHub Projekt als ein Issue 🐙

**Comment by dnns01** [comment]
Ja ich verstehe was du meinst. Ich denke aber wie auch bei #156 schon erwähnt, zum Teil dürfte sich das erledigen, wenn wir auf Slash Commands umsteigen. Nicht komplett, aber teilweise auf jeden Fall. Da muss man dann mit Ruhe nochmal durchgehen.
