### ISSUE TITLE
Github Issues aus Discord erstellen

### ISSUE THREAD

**Issue by dnns01** [FU-Hagen-Discord/fernuni-bot#14]
Ähnlich wie Decky derzeit, soll über das Command `!idee` die Möglichkeit geschaffen werden, Feature Requests in Form von Github issues einzubringen.

**Comment by L-MzK** [comment]
Kommt die !card (mod only) Anweisung dann auch gleich mit?

**Comment by L-MzK** [comment]
Zusätzliche Funtkion: Boty soll neue ungelabelte Issues von der Community abstimmen lassen.

**Comment by dnns01** [comment]
> 
> 
> Kommt die !card (mod only) Anweisung dann auch gleich mit?

Natürlich :)

**Comment by dnns01** [comment]
Aktuell nur Basisfunktionalität implementiert. `!idee` und `!card` commands wie bisher von Decky gewohnt sollen implementiert werden. Weitere Features, wie das kommentieren über Discord oder hier erstellte, ungelabelte Issues über Discord zur Abstimmung zu geben folgen später
