### ISSUE TITLE
Module-help soll expliziter sein (channelgebunden)

### ISSUE THREAD

**Issue by McBotface** [FU-Hagen-Discord/fernuni-bot#142]
Es soll eine kleine Ergänzung / Textänderungen (Text muss ich mir angucken) beim Hilfseintrag zum Modul-Kommando kommen, dass dieser channelgebunden ist und bspw. im bot-übungsplatz oder in Botys DMs nichts ergeben wird.

**Comment by fastrde** [comment]
Hilfetext ergänzen oder Fehlermeldung liefern, sodass klar wird, dass dieses Kommando nur in Kurs-Kanälen ausgeführt werden kann.

**Comment by ffaadd** [comment]
Hilfetext ergänzen oder Fehlermeldung liefern, sodass klar wird, dass dieses Kommando nur in Kurs-Kanälen ausgeführt werden kann.

**Comment by Lou-M** [comment]
Zusätzlich: Fehlermeldung, wenn !module in einem nicht-Kurs-Channel ausgeführt wird.

**Comment by dnns01** [comment]
Inzwischen umgesetzt. Module Command in allen Channels möglich, bei Angabe der Modulnummer. Wenn kein Modulkanal und keine Modulnummer angegeben, gibt es eine entsprechende RÜckmeldung.
