### ISSUE TITLE
Kursnummer als neuer optioneller Parameter von `!module`

### ISSUE THREAD

**Issue by Lou-M** [FU-Hagen-Discord/fernuni-bot#143]
📆 Dieses Issue sollte ausschließlich an anderen Tagen als an Montagen begutachtet werden.
![image](https://user-images.githubusercontent.com/73669620/151800043-fe2464c5-0689-4631-82e8-a948419b1fab.png)

**Comment by ffaadd** [comment]
Es wird sowohl die Kursnummer aus dem Kanalnamen als auch der Studiengang aus der Rolle des Aufrufenden.  Den Studiengang kann man optional als Parameter bereits angeben, was die optionale eingabe einer Kursnummer verhindert. bzw. bedingt, dass man auch den Studiengang angibt, wenn man die Kursnummer angeben möchte.

**Comment by Lou-M** [comment]
Oh ich wusste nicht, dass ein optioneller Parameter den anderen ausschließt. 
Bei Slash Commands scheint es nicht der Fall zu sein: beim Timer kann ich bspw nur den Namen oder nur die Pausenzeit festlegen 🤔

Der Gedanke hinter der Anfrage ist ja, dass man so in anderen Kanälen (bspw im bot-übungsplatz) die Modulinfos eines beliebigen Kurses abrufen könnte.
Klingt dann aber mehr nach einem größeren Aufwand, wenn es nur über einen Wandel zum Slash Command ginge.

**Comment by ffaadd** [comment]
evtl. könnte man beide optionalen Parameter als Kursnummer und Studiengang betrachten und anhand des Parameters entscheiden welcher welcher ist.
`/^[0-9]+$/` => Kursnummer
`/^[a-zA-Z]+$/` => Studiengang

**Comment by Lou-M** [comment]
Durch die neusten [Major Improvements ™️](https://github.com/FU-Hagen-Discord/fernuni-bot/commit/eee1330360c84f85021d069181020989e328bcd4) (Boty Goes Slash - hoffentlich den richtigen Commit erwischt) umgesetzt 🥳
