### ISSUE TITLE
Aliase für Text-Commands einrichten

### ISSUE THREAD

**Issue by McBotface** [FU-Hagen-Discord/fernuni-bot#149]
**Nicht nur** ~~🥳 als Alias für `!party`~~

![image](https://user-images.githubusercontent.com/73669620/156212696-cb8a7f69-b5a9-471d-b85f-7163379e614f.png)
@dnns01 
> Kopieren ist weniger aufwändig im ersten Schritt. Aber macht es aufwändiger zu maintainen. Und Alias ist sauberer.

**Comment by dnns01** [comment]
Mit Slash Commands werden Aliase wohl eher kein Thema mehr sein.
