### ISSUE TITLE
Kommando gelingt -> ✅-Reaktion von Boty

### ISSUE THREAD

**Issue by Lou-M** [FU-Hagen-Discord/fernuni-bot#156]
Als Bestätigung dafür, dass das Kommando geklappt hat.

Für:

- [ ] `!help`
- [ ] die [Voice-Sperre](https://github.com/FU-Hagen-Discord/fernuni-bot/blob/develop/cogs/voice.py),
- [ ] [Lerngruppen](https://github.com/FU-Hagen-Discord/fernuni-bot/blob/develop/cogs/learninggroups.py)
    - [ ] die Anfrage nach einer Lerngruppe,
    - [ ] das Erstellen von einer Listen-KursÜberschrift
  
Sollte mir / euch noch was sinnvolles einfallen, kann es ja der Liste hinzugefügt werden ^^

*Dem Issue #11 untergeordnet (das am Besten eher zu einem Projekt umgewandelt werden sollte)*

**Comment by dnns01** [comment]
Nope^^ Nix mit ✅ Reaktion. Das wird entsprechend auf Slash Commands umgebaut und da ist quasi die Reaktion auf das Command schon eingebaut.

**Comment by Lou-M** [comment]
Alles davon, auch die Voice-Sperre?

**Comment by dnns01** [comment]
Warum nicht? Also mein Ziel ist, soweit möglich alles auf Slashcommands umzustellen

**Comment by Lou-M** [comment]
Alles klar, ich dachte, dass sowas wie Voice-Sperre eben so weit unten in der Prio-Liste wär, dass es gar nicht für Slash-Command ansteht.
(Ich meine außerdem, dass es eine Anzahlbegrenzung an Slash Commands gibt, die eine App haben kann)

**Comment by dnns01** [comment]
Muss man nochmal näher nachschauen auf jeden Fall, ob es Limits gibt und wo die wenn liegen. Aber mein Ziel wäre es auf jeden Fall sowas als Slash Command haben zu wollen

**Comment by dnns01** [comment]
Konzeptionell hat jedes Slash Command irgendeine Form der Reaktion. Mit dem Umstieg auf Slash Commands wird sich das also automatisch erledigt haben
