### ISSUE TITLE
Hilfstexte des Lerngruppensystems eindeutiger machen

### ISSUE THREAD

**Issue by Lou-M** [FU-Hagen-Discord/fernuni-bot#160]
Hauptsächliches Thema: 
- Geschlossene und Offene Gruppen 
vs. 
- Gelistet und ungelistet

Beispiel:
- [x] #230
> Offene Lerngruppen können nicht aus der Lerngruppenliste entfernt werden. Führe `!lg close` aus um die Lerngruppe zu schließen, oder `!lg private` um diese auf privat zu schalten.
- [x] #231

**Comment by Lou-M** [comment]
- [x] Willkommensnachricht bei LG-Erstellung - *[Vorschlag](https://discord.com/channels/353315134678106113/897922675949846588/955465237098803200)*

**Comment by dnns01** [comment]
In der Art und Weise, wie das bisher geplant war, mit Hilfetexten dürfte das in Zukunft ja nicht mehr der Fall sein. Aber ich denke an dem Punkt könnt ihr mit der Änderung des Lerngruppen Systems zusammenarbeiten @ffaadd und @Lou-M

**Comment by Lou-M** [comment]
#231 mit #229 geschlossen, damit ist dieses (diese) Issue ebenfalls geschlossen
