### ISSUE TITLE
Obsidian-Channel

### ISSUE THREAD

**Issue by McBotface** [FU-Hagen-Discord/fernuni-bot#167]
Was haltet ihr davon, wenn wir einen Obsidian-Channel einrichten? Es scheint ein grösser werdendes Interesse an der Verwendung von Obsidian im Studium zu geben. Obsidian hat als Tool grosses Potential um unseren Lernalltag enorm zu erleichtern. Momentan wird das im Lernen-lernen-Channel diskutiert. Die Möglichkeiten in Obsidian sind umfangreich genug, dass das einen eigenen Channel verdient. Und es hättet den Vorteil, dass sich dann der Lernen-lernen-Channel wieder auf Lernmethodiken fokussieren kann.
- *Vorschlag von Malphabet*

**Comment by Lou-M** [comment]
# Anregungen / Anmerkungen

## Gegenargumente
Frühere Channels zu einem spezifischen Tool / Sprache wurden in der Vergangenheit zusammengefasst
-  wegen Inaktivität und 
- um die Anzahl an Channels übersichtlicher zu machen.

## Alternative
- Thread unter lernen-lernen
- Zusätzlicher Lerntools Channel stattdessen

**Comment by Lou-M** [comment]
Entscheidung des OrgaTeams: mehrheitlich dagegen, einen eigenen Channel / Thread für einen einzelnen Lerntool zu haben.
Lernen-lernen (ehem. Lerntools) ist der richtige Ort, um darüber zu sprechen.
