### ISSUE TITLE
Rollen-Vergabe aktualisieren

### ISSUE THREAD

**Issue by McBotface** [FU-Hagen-Discord/fernuni-bot#170]

**Comment by Lou-M** [comment]
- [ ] Saisonalrolle weg
- [ ] ErstiRollen selbst vergeben / entfernen
- [ ] unschöne Studiengangsrollen weg
- [ ] Farbrollen mit nützlicheren Emojis schmücken

**Comment by dnns01** [comment]
Alles erledigt, bis auf letzten Punkt. Weiß aber auch nicht, welche Emojis besser für die Farbrollen sein könnten, als die Farbe, die man sich selbst damit zuteilt.
