### ISSUE TITLE
Lerngruppenverwaltung auf slashcommands umstellen

### ISSUE THREAD

**Issue by ffaadd** [FU-Hagen-Discord/fernuni-bot#177]

**Comment by dnns01** [comment]
Lerngruppenverwaltung ist auf slash commands umgestellt.

**Comment by Lou-M** [comment]
> Lerngruppenverwaltung ist auf slash commands umgestellt.

Was letztes Jahr so alles schon erreicht war 😄 
Sollte das wieder geöffnet werden?

**Comment by dnns01** [comment]
Ne, nich wirklich. Ich sag mal das ToDo ist weniger das umstellen, sondern mehr das aktualisieren.
