### ISSUE TITLE
Rename Owner in Lg-module

### ISSUE THREAD

**Issue by Lou-M** [FU-Hagen-Discord/fernuni-bot#178]
Verantwortliche/ Organisatorin
statt `Besitzerin`

**Comment by jmb-oddbook** [comment]
Hi @Lou-M, 
ich würde gerne dieses Issue als first issue bearbeiten. Ist das in Ordnung?
Eine Rückfrage noch. Im Lg-module erscheint mehr als einmal `Besitzer(in)`, das Issue ist schon so gemeint, daß das überall geändert werden sollte, oder?
Ich bin auf dem FU-Discord als _amatenki#6042_ zu finden.
Grüße, Jessica

**Comment by Lou-M** [comment]
@jmb-oddbook toll dass du zum Bot beitragen möchtest!
Ich habe zwar den Issue erstellt *und denke, dass es sehr willkommen wäre*.
Das Lerngruppensystem-Modul fällt aber mehr in **@ffaadd s Zuständigkeit**, der damit auch angepingt ist und sich bestimmt dazu äußern wird. 

Inhaltlich:
- der Begriff Besitzerin kommt tatsächlich mehr als ein Mal vor und 
- ich finde (zwischen `Verantwortliche` und `Organisatorin`) **Organisatorin** besser, weil es direkter den Eindruck vermittelt, dass es nicht nur um die Erstellung oder um Führung geht, aber auch bspw darum am Ball zu bleiben, dass Termine stattfinden.

**Comment by jmb-oddbook** [comment]
Organisatorin würde ich persönlich auch besser finden, es klingt auch mehr nach Gruppe und weniger nach Hierarchie.
An einigen Stellen würde auch _Erstellerin_ passen, aber Einheitlichkeit ist auch ein Gesichtspunkt, oder?

Muß ich für Tippfehler ein neues Issue erstellen oder darf ich die gleich mit wegbügeln? Ich mach das hier zum ersten Mal.

**Comment by ffaadd** [comment]
@jmb-oddbook 👋
Lou denkt da genau richtig. Ich hab absolut nichts dagegen, wenn du dir das Issue schnappst. Da es hier eh um Textkorrekturen geht, ist das ausmerzen von Typos auch gar kein Problem (ist glaube ich eh nie ein Problem ;) ).

**Comment by jmb-oddbook** [comment]
Super 👍 Dann schnapp ich mir das Issue

**Comment by jmb-oddbook** [comment]
Ihr lasst mich wissen ob ich etwas nachbessern soll. :wave:

**Comment by Lou-M** [comment]
Du warst schnell 😀
Ich kanns mir gerne anschauen / reviewen, @dnns01 hat dann die Macht, es durchzuwinken.

**Comment by jmb-oddbook** [comment]
Ich hatte gestern einen freien Abend :grinning:
