### ISSUE TITLE
Umfragenarten: anonym, Namensnennung nach Schließung

### ISSUE THREAD

**Issue by Lou-M** [FU-Hagen-Discord/fernuni-bot#18]
Zusätzlicher Parameter `anonym` ?

**Comment by dnns01** [comment]
Wie meinst du das???

**Comment by L-MzK** [comment]
Momentan kann man nach dem Schließen einer Umfrage nicht mehr sehen, wer für was abgestimmt hat. 
Es ist aber oft relevant (wer kann wann?/ wer möchte was übernehmen? usw). Also wäre die Option “Namen der User werden nach dem Schließen erwähnt” ganz gut, meine Vermutung wäre dass es sogar die default Einstellung sein könnte.

**Comment by dnns01** [comment]
Das ist im Prinzip das, was wir ursprünglich bei den Polls hatten. Das hat nur bei großen Umfragen dazu geführt, dass die Embed nachricht zu lang wurde, weswegen die Nachricht nicht verschickt werden konnte. Das gibt es hierbei also zu beachten.

**Comment by L-MzK** [comment]
Dann vielleicht als optionaler parameter `<transparent?>`

**Comment by dnns01** [comment]
Darum ging es mir geradnicht. Ich wollte nur mitteilen, dass das schon mal drin war, und was damals das Problem war, wieso ich es erst mal rausgenommen habe, weil ich das Problem nicht auf die Schnelle beheben konnte.

**Comment by L-MzK** [comment]
Verwandte Frage:
Könnte man (vielleicht über dislash und Buttons @samari-k ?) eine parallele Art von Umfragen anbieten, die 100 % anonym wär, auch während der Stimmabgabe?
Es gibt durchaus Themen, bei denen das ein großer Plus wäre.

**Comment by dnns01** [comment]
Anonym wird schwer. Pseudonym sollte aber möglich sein (Also der Bot sollte halt einfach wissen, wer wofür abgestimmt hat, um mehrfach Abstimmungen zu verhindern)

**Comment by L-MzK** [comment]
> Anonym wird schwer. Pseudonym sollte aber möglich sein

Vielen Dank, das meinte ich!
An sich löscht Boty bereits Reaktionen in der Rollenvergabe, demnach bräuchte man nicht unbedingt Knöpfe, wenn ich darüber nachdenke.

**Comment by dnns01** [comment]
Ja, wobei das löschen der Reaktionen auch nicht immer ganz zuverlässig funktioniert, wie sich zeigt.

**Comment by ffaadd** [comment]
Ja ich glaube auch, das Buttons mit "Boty merkt sich intern wer gedrückt hat" die beste Variante dafür ist. Allerdings haben wir noch das Problem, dass die Buttons nicht mehr funktionieren, wenn Boty neu gestartet wurde. Was bei einer Umfrage die ne Woche läuft evtl. uncool ist.

**Comment by samari-k** [comment]
man kann für den ClickListener der Buttons ein timeout setzen (damit könnten Umfragen nach dem timeout auch direkt automatisch "ausgewertet" werden)
man könnte die Umfragen deren timeout noch nicht abgelaufen ist in einer Datei speichern und nach nem reconnect den entsprechenden ClickListener neu starten... keine Ahnung, ob das so simpel funktioniert, klingt für mich aber erstmal plausibel und nen Versuch wert

**Comment by samari-k** [comment]
Statt einzelner ClickListener pro Nachricht kann man das globale on_button_click Event nutzen, das läuft dann auch nach nem Reconnect.

**Comment by L-MzK** [comment]
Könnten das dann zwei Subcommands werden?
`!poll transparent`: nach dem Schließen wird aufgelistet, wer wofür abgestimmt hat
`!poll anon(ymous)`: während der Abstimmung werden die Namen nicht angezeigt
Wer nur `!poll` schreibt, kriegt anonymous.
