### ISSUE TITLE
Fehler (?) des Befehls "!links edit-link"

### ISSUE THREAD

**Issue by dwiawdfi** [FU-Hagen-Discord/fernuni-bot#186]
Der Ausdruck `!links edit-link "Google" "www.google.com" "Google" www.google.com` wird nicht akzeptiert (so Boty: "Ich konnte den Link leider nicht finden").

**Comment by dnns01** [comment]
Command funktioniert, wie in der Hilfe beschrieben.
`!links edit-link <topic> <title> <new_title> <new_topic?> <new_link?>`
Die Syntax ist nicht die einfachste, mit Slash Commands sollte das besser werden.
