### ISSUE TITLE
Custom Reaktion-Emotes für Umfragen

### ISSUE THREAD

**Issue by L-MzK** [FU-Hagen-Discord/fernuni-bot#19]
Als default weiterhin Buchstaben (regional_indicator_a usw), optional mit selbstausgewählten Emotes?

Weil:
- passender zu den Optionen ("Katalog N" - Buchstabe E...),
- Customisierung Spaß macht.

![Confusing](https://user-images.githubusercontent.com/73669620/117138311-2499bc80-adab-11eb-9674-4eb1caa52257.png)

**Comment by dnns01** [comment]
Bin mir gerade nicht sicher, wie man das am besten löst. Jetzt nicht unbedingt der Code, sondern wie man so nen Poll erstellen soll.

**Comment by L-MzK** [comment]
Ich weiß nicht wie machbar es wäre, es so umzusetzen aber ich dachte `!poll "Titel" "🥳 Option 1" "🧐 Option 2"`usw.
- Entweder mit Bedingung: alle Optionen müssen dann mit Emoji + Leerzeichen beginnen (und bspw. ein optionaler Parameter `custom réactions?`)
- oder automatisch erkennen: Emoji + Leerzeichen zu Beginn der Option -> emoji ersetzt den default Buchstabe.

**Comment by ffaadd** [comment]
Du bräuchtest irgendwas in die Richtung KeyValue Pairs aus emote und answer. Dafür brauchst du irgendeinen Trenner. Ich hätte spontan `:` vorgeschlagen, aber der ist in den Strings zum erzeugen der Emotes vorhanden, also eher ungeeignet. Im folgenden Bespiel hab ich mal `$` genommen weil ich gerade nichts besseres zur Hand hab. 

!poll ":100:$Hundert tolle Dinge?" ":+1:$Daumen hoch?" "normale Anwort ohne Dollarzeichen (ist dann ein blaues A)"
`!poll ":100:@Hundert?" ":+1:$Daumen hoch?" "normale Anwort ohne Dollarzeichen (ist dann ein blaues A)"`

Und dann parsen und wenn `$` im String ist in emote uns answer splitten. Aber ich finde `$` nicht gut als Trenner und weiß auch nicht ob die Eingabe dann nicht noch weiter an Komplexität zulegt. 

> Neuer Poll
> :100: - Hundert tolle Dinge?
> :+1: - Daumen hoch?
> A -  normale Antwort (ist dann ein blaues A)
> Stimme ab:
:100: :+1: A

**Comment by ffaadd** [comment]
> Ich weiß nicht wie machbar es wäre, es so umzusetzen aber ich dachte `!poll "Titel" "🥳 Option 1" "🧐 Option 2"`usw.
> 
> * Entweder mit Bedingung: alle Optionen müssen dann mit Emoji + Leerzeichen beginnen (und bspw. ein optionaler Parameter `custom réactions?`)
> * oder automatisch erkennen: Emoji + Leerzeichen zu Beginn der Option -> emoji ersetzt den default Buchstabe.

Wenn man diese Idee weiterdenkt könntest du auch nach einem `:` am Anfang der Antwort parsen und dann dann gucken ob ohne Lehrzeichen ein String mit abschließendem `: `  folgt. Dann weißt du, dass ein emote am Anfang steht und könntest das einfach Frech als Option anbieten. Dann 

`!poll ":100: custom Emote Antwort da : am Anfang" "normale Antwort da kein : am Anfang"`

> :100:  - custom Emote Antwort da : am Anfang
> A - normale Antwort da kein : am Anfang

Find ich charmanter als den KeyValue Splitter weil das die natürlichere Eingabe ist.

**Comment by dnns01** [comment]
> 
> 
> Ich weiß nicht wie machbar es wäre, es so umzusetzen aber ich dachte `!poll "Titel" "🥳 Option 1" "🧐 Option 2"`usw.
> 
>     * Entweder mit Bedingung: alle Optionen müssen dann mit Emoji + Leerzeichen beginnen (und bspw. ein optionaler Parameter `custom réactions?`)
> 
>     * oder automatisch erkennen: Emoji + Leerzeichen zu Beginn der Option -> emoji ersetzt den default Buchstabe.

Manchmal sollte man einfach morgens nicht aufstehen 🤦 Ich war die ganze Zeit in Gedanken so dermaßen daneben. Klar dann passt das auch, was ich ursprünglich mal als Idee im Kopf hatte.
