### ISSUE TITLE
Umstieg von disnake zurück zu discord.py

### ISSUE THREAD

**Issue by dnns01** [FU-Hagen-Discord/fernuni-bot#191]
Da discord.py weiter macht und inzwischen v2.0 released wurde, können wir doch wieder zurück gehen zu dpy. Dabei sollten auch die Commands zu Slash Commands gemacht werden
Zu migrieren:
- [x] Appointments
    - [x] `!add-poointment` => `/appointments add`
    - [x] `!appointments` => `/appointments list`
- [x] Github
    - [x] `!idee` => `/idee`
    - [x] `!card` => `/card`
- [x] Learninggroups
    - [x] `!lg update` => `/lg update`
    - [x] `!lg header` => `/lg header`
    - [x] `!lg add` => `/lg add`
    - [x] `!lg request` => `/lg request`
    - [x] `!lg show` => `/lg show`
    - [x] `!lg hide` => `/lg hide`
    - [x] `!lg debug` => `/lg debug`
    - [x] `!lg open` => `/lg open`
    - [ ] ~~`!lg close`~~
    - [X] `!lg private`  => `/lg private`
    - [ ] ~~`!lg rename`~~
    - [ ] ~~`!lg archive`~~
    - [x] `!lg organizer` => `/lg organizer`
    - [x] `!lg addmember` => `/lg add-member`
    - [x] `!lg removemember` => `/lg remove-member`
    - [x] `!lg members` => `/lg members`
    - [x] `!lg id` => `/lg id`
    - [x] `!lg join` => `/lg join`
    - [x] `!lg kick` => `/lg kick`
    - [x] `!lg leave` => `/lg leave`
- [x] Links
    - [x] `!links` => `/links list`
    - [x] `!links add` => `/links add`
    - [x] `!links remove-link` => `/links remove-link`
    - [x] `!links remove-topic` => `/links remove-topic`
    - [x] `!links edit-link` => `/links edit-link`
    - [x] `!links edit-topic` => `/links edit-topic`
- [x] ModuleInformation
    - [x] `!module` => `/module` 
    - [ ] ~~`!module update`~~
    - [x] `!module handbuch` => `/module topic: handbuch`
    - [x] `!module leseprobe` => `/module topic: probe`
    - [x] `!module info` => `/module topic: info`
    - [x] `!module aufwand` => `/module topic: aufwand`
    - [x] `!module mentoriate` => `/module topic: mentoriate`
    - [x] `!module prüfungen` => `/module topic: pruefungen`
- [x] News
- [x] Polls
    - [x] `!poll` => `/polls add`
    - [ ] ~~`!poll suggest`~~ => Wird nicht mehr verwendet
    - [ ] ~~`!poll edit`~~ => Wird nicht mehr verwendet
- [x] ~~Support~~ModMail
- [x] TextCommands
    - [x] `!commands list` => `/commands list`
    - [x] `!commands add` => `/commands add`
    - [x] `!commands edit` => `/commands edit`
    - [x] `!commands remove` => `/commands remove`
    - [ ] ~~`!commands edit-help`~~
    - [ ] ~~`!commands edit-category`~~
- [x] Timer
- [x] Voice
    - [x] `!voice` => `/voice`
- [x] Welcome
    - [ ] ~~`update-welcome`~~
- [x] XKCD
    - [x] `!xkcd` => `/xkcd`

Zu entfernen, weil osolet geworden:
- [x] Calmdown
- [x] ElmStreet
- [x] Roles
- [x] Help

Deprecated (Cogs, die evtl. gar nicht mehr oder nur zeitweise gebraucht werden)
- [x] Christmas
    - [ ] `!advent`
    - [ ] `!advent list`
    - [ ] `!advent assign`
    - [ ] `!advent reassign`
    - [ ] `!advent remaining`
- [x] EmojiHunt
    - [ ] `!leaderboard`
- [x] ChangeLog

**Comment by ffaadd** [comment]
Bin gerade an den Learninggroups, ansonsten hab ich angehakt, was fertig umgezogen und rudimentär getestet ist. Die einzelnen Kommandos müssen wir dann nochmal in einem größeren Test auf QA durchtesten.

**Comment by dnns01** [comment]
ToDo: Nach Deploy `text_commands.json` anpassen an aktuelles Format
