### ISSUE TITLE
Boty archiviert nicht mehr wenn die Archiv-Kategorie voll ist (50+)

### ISSUE THREAD

**Issue by Lou-M** [FU-Hagen-Discord/fernuni-bot#205]
Und es gibt auch keine Nachricht von Boty im Chat dazu, nur vorwurfsvolles Schweigen ^^

Vorschlag: 
- Automatische Erstellung einer neuen Archivkategorie +
- Benachrichtigung in den Mods Channels, dass man da aufräumen könnte

**Comment by dnns01** [comment]
Wird nicht weiter benötigt. Lerngruppen werden in Zukunft nicht mehr archiviert.
