### ISSUE TITLE
xkcd Feature 

### ISSUE THREAD

**Issue by samari-k** [FU-Hagen-Discord/fernuni-bot#21]
Wie wär's mit nem !xkcd command, der Boty random xkcd-comics Posten lässt? Oder mit zusätzlichem Argument !xkcd 221 - um einen bestimmten Comic über seine ID auszuwählen.

Man könnte zwar meinen, die Nachfrage dafür wäre nicht da, aber ich wette, die steigt mit dem Angebot.

**Comment by ffaadd** [comment]
Kleine Hilfestellung falls sich hier jemand dran versuchen mag:
"API Beschreibung" unter https://xkcd.com/json.html

1. json vom aktuellen Bild fetchen `max=data.num` (`num` ist die Nummer des Bildes, so hat man die max Anzahl)
2. `r`=random `0` bis `max`
3. json von Bild mit Nummer `r` fetchen
4. `data.img` im Chat posten

Anmerkung: Das fetchen muss non-blocking erfolgen `aiohttp` ist die richtige Library dafür. Beispiele gibt's schon im Boty-code

**Comment by L-MzK** [comment]
Ganz langweiliger Vorschlag aber: als Reaktion auf dem Text-command !xkcd 
-> https://c.xkcd.com/random/comic/ ?

**Comment by ffaadd** [comment]
> Ganz langweiliger Vorschlag aber: als Reaktion auf dem Text-command !xkcd
> -> https://c.xkcd.com/random/comic/ ?

oh. wusste nicht, dass das geht. Das ist ja fast ein quickwin. Bis auf den Punkt "direkt über ID" ist es damit ja schon implementiert.

**Comment by L-MzK** [comment]
Ja... wäre auch zu einfach gewesen ^^' ich habe (noch) keine Ahnung von den schönen Sachen, die du hier (#issuecomment-833093618) erwähnt hast und überlasse diese Aufgabe daher gerne jemanden, der / die sich damit auskennt 😀

**Comment by ffaadd** [comment]
https://xkcd.com/license.html beachten.
Das Bild muss mit Attribution gepostet werden.
