### ISSUE TITLE
!idee noch in Botys Hilfe

### ISSUE THREAD

**Issue by Lou-M** [FU-Hagen-Discord/fernuni-bot#212]
- Hilfseintrag entfernen?
- GitHub-Integration entfernen? 
- Perspektiven der GitHub Integration nach dem Update?

**Comment by dnns01** [comment]
=> Hilfseintrag sollte auf jeden Fall entfernt werden
=> Die Integration komplett entfernen sehe ich nicht. Vor allem weil das in Zukunft ja (nur eben auf andere Weise) weiter genutzt werden soll. Und `/card` für Mods darf meiner Meinung nach wie bisher bestehen bleiben.

**Comment by Lou-M** [comment]
Finde ich gut!

**Comment by dnns01** [comment]
Wird nicht weiter benutzt
