### ISSUE TITLE
Umstellung zu Modulnummern broke !module mentoriate?

### ISSUE THREAD

**Issue by Lou-M** [FU-Hagen-Discord/fernuni-bot#223]
!Module Mentoriate funktioniert nicht mehr? 
Ungünstig zu Zeiten des Semesterwechsels.

Issue erstellt, um das „wir arbeiten dran“ zu konkretisieren ✍🏼

![IMG_9245](https://github.com/FU-Hagen-Discord/fernuni-bot/assets/73669620/9f9da08c-0610-4b40-9755-774b28730042)

**Comment by dnns01** [comment]
Funzt wieder.
