### ISSUE TITLE
Vereinfachte Begrüßung neuer Discord-Mitgliedern durch pingbare Neuankömmling-Rolle

### ISSUE THREAD

**Issue by Lou-M** [FU-Hagen-Discord/fernuni-bot#26]
Um die Begrüßung in #grüß-dich weniger blockig und mühsam zu machen -> wäre es denkbar, dass es folgende (mods-only) Funktion gibt?

> Ab `<jetzt>` kriegt jedes neue Mitglied die (_wenn es geht nur von den Mods_ pingbare) Rolle `neu-hier` (vorschlag?) - die Rolle wird bei allen entfernt, die sie vor `<jetzt>` besaßen.

Den "Knopf" könnte man nach jeder kollektiven Begrüßung tätigen und damit nicht 1000 (oder 3) mentions machen, sondern nur ein Mal die Rolle.

**Comment by dnns01** [comment]
Das wird glaub ich so nicht funktionieren, wie bisher. Die Erwähnung wird den Leuten vermutlich nicht mehr angezeigt, sobald man ihnen die Rolle wegnimmt.

**Comment by L-MzK** [comment]
Ja, das liegt Nahe, hatte ich nicht bedacht. 
Ich würde es als nice-to-have new feature labeln. 
Falls man dafür keinen sinnvollen einfachen Weg findet... `wontfix` 🦢
