### ISSUE TITLE
Discord / Studiums FAQ

### ISSUE THREAD

**Issue by dnns01** [FU-Hagen-Discord/fernuni-bot#28]
Irgendeine Form von FAQ erstellen. Wie und wo bleibt noch zu diskutieren. FAQ einmal den Discord betreffend, aber auch ganz generell auf das Studium bezogen

**Comment by dnns01** [comment]
@Lou-M Kann eigentlich geschlossen werden, oder?

**Comment by Lou-M** [comment]
Ja stimmt, Issue kann geschlossen werden 💃
 Closed - FernUni FAQ steht noch an aber dafür braucht man keinen Issue.
