### ISSUE TITLE
Links in Channels verwalten

### ISSUE THREAD

**Issue by dnns01** [FU-Hagen-Discord/fernuni-bot#33]
Derzeit können lediglich Links hinzugefügt werden. Ändern von Links oder Titeln, sowie Löschen ist nicht möglich. Das muss sich ändern!

**Comment by ffaadd** [comment]
in diesem Zuge sollte daraus ein Modul mit Subkommandos gemacht werden.
```
!links - Links anzeigen
!links add - Link hinzufügen
!links edit - Link editieren
!links remove - Link entfernen
!links add-group - Titel hinzufügen (wird das gebraucht?)
!links edit-group - Titel editieren
```

**Comment by L-MzK** [comment]
Die !links Funktion ist fast gleichnamig mit dem text-Kommando !link (das den Einladungslink zum Discord-Server bereitstellt).
Möglicherweise verwirrend?

**Comment by dnns01** [comment]
> 
> 
> in diesem Zuge sollte daraus ein Modul mit Subkommandos gemacht werden.
> 
> ```
> !links - Links anzeigen
> !links add - Link hinzufügen
> !links edit - Link editieren
> !links remove - Link entfernen
> !links add-group - Titel hinzufügen (wird das gebraucht?)
> !links edit-group - Titel editieren
> ```

Ja genau das meinte ich...

**Comment by dnns01** [comment]
> 
> 
> Die !links Funktion ist fast gleichnamig mit dem text-Kommando !link (das den Einladungslink zum Discord-Server bereitstellt).
> Möglicherweise verwirrend?

Das ist der Grund, wieso der Link zu Discord jetzt auch über `!discord` abrufbar ist. Dadurch kann `!link` entfernt werden
