### ISSUE TITLE
Ping-Rollen für Fakultäts- bzw. FernUni-Fristen

### ISSUE THREAD

**Issue by Lou-M** [FU-Hagen-Discord/fernuni-bot#38]
Eine oder mehrere Rollen in #rollen-vergabe, Umsetzung vielleicht über die [Appointment-Funktion](https://github.com/FU-Hagen-Discord/fernuni-bot/blob/master/appointments_cog.py).
Reminder zum Beginn, zum Ende und vielleicht etwas dazwischen.

Vorschlag für die Rolle(n): 
- Fristenjägerin oder -junkie / "aufmerksame Fristeneinhaltung" oder
- straightforward bei mehreren Rollen "Klausurfristen" "Rückmeldefristen" usw.

Vorschläge für Fristen:
- Rückmeldefrist & - Belegungsfrist (+ mit der letzten Chance, z.B. in diesem SoSe der 15. Mai) - [Semestertermine der FernUni](https://www.fernuni-hagen.de/studium/fernstudieren/semestertermine.shtml)
- Klausuranmeldefrist (idealerweise mit Link zum [POS](https://pos.fernuni-hagen.de/) + zur Seite im Prüf.info-Heft _(edit: Link raus, war vom WiSe20)_ mit den Gebührenbestimmungen)

**Comment by dnns01** [comment]
Da sprichst du was an, das mir auch schon ne weile irgendwie im Kopf herumgeistert. Also grundsätzlich bin ich dafür 👍

**Comment by ffaadd** [comment]
Bin auch dafür. Wir müssen nur mal sehen woher wir welche Fristen sinnvoll beziehen.

**Comment by Lou-M** [comment]
Letzter Stand ging eher in die Richtung: "Keine Rolle, aber automatische Erinnerung @everyone bei den wichtigsten Fristen".

=> Umbernennung des Issues?

**Comment by dnns01** [comment]
Die Fristen automatisch zu beziehen wird sicher nicht funktionieren. 
@Lou-M Besser manuell. Für die paar Fristen, die es gibt  kann man sich in ja nen Appointment setzen um dran zu denken, rechtzeitig zu erinnern. Und dann entweder an @everyone oder @News oder über eine neu zu erstellende Rolle. Für die Rolle ist aber nur ein Update der json nötig und kein Code Chance.
