### ISSUE TITLE
Zusätzliche Funktion: Boty soll neue ungelabelte Issues von der Community abstimmen lassen.

### ISSUE THREAD

**Issue by dnns01** [FU-Hagen-Discord/fernuni-bot#40]
Zusätzliche Funktion: Boty soll neue ungelabelte Issues von der Community abstimmen lassen.

_Originally posted by @L-MzK in https://github.com/FU-Hagen-Discord/fernuni-bot/issues/14#issuecomment-832652245_

**Comment by ffaadd** [comment]
evtl. sollten wir da lieber ein `community` label oder so für einführen, damit nicht issues wie *bugfixes* oder *code aufräumen* aus versehen auf dem discord landen.

**Comment by dnns01** [comment]
Das wäre dann zumindest kein Automatismus. Aber vielleicht gar keine so schlechte Idee.

**Comment by dnns01** [comment]
Eigentlich keine wirkliche Verwendung denk ich.
