### ISSUE TITLE
Beim wiederholtem Aufruf von !prokrastination -> "{Username} , so schlimm? Gib doch lieber mal !motivation ein. Das bringt dich weiter!"

### ISSUE THREAD

**Issue by McBotface** [FU-Hagen-Discord/fernuni-bot#43]

**Comment by L-MzK** [comment]
> Ab 3 an einem Tag, oder  5 in der Woche

_Vorschlag von Tolga am 16/05/2021_

**Comment by ffaadd** [comment]
- jeder Aufruf von `!prokrastination` muss mit `id` des users und `zeitstempel` gespeichert werden
- bei jedem Aufruf muss geprüft werden wie viele Aufrufe entweder innerhalb von 24h oder mit gleichem Datum (je nachdem wie man es möchte) stattgefunden haben
- bei jedem Aufruf muss geprüft werden wie viele Aufrufe innerhalb von 7d stattgefunden haben.
- was passiert, wenn Boty bereits reagiert hat und erneut `!prokrastination` aufgerufen wird?
- wie werden ältere aufrufe > 7d aus der Datenbasis entfernt?

Für mich ist der Aufwand für den Nutzen zu hoch. Wenn das jemand als Programmierübung machen möchte hab ich aber generell nichts gegen das Feature.

**Comment by dnns01** [comment]
Da Prokrastination ein Text Command ist, und der Sinn dieser Commands ist, dass man einfach Texte dafür reingönnen kann, wäre dieser Vorschlag im Prinzip das Gegenteil.
