### ISSUE TITLE
Verzeichnisstruktur überarbeiten

### ISSUE THREAD

**Issue by ffaadd** [FU-Hagen-Discord/fernuni-bot#45]
Die Verzeichnisstruktur von Boty ist gewachsen und nun da mehrere Entwickler daran arbeiten sollte diese vereinheitlicht werden.
Anstatt die Änderungen zu beschreiben, fand ich's einfacher diese per Refactor durchzuführen. Das Ergebnis habe ich als ersten Entwurf unter https://github.com/FU-Hagen-Discord/fernuni-bot/tree/directory-structure abgelegt.  

- alle Cogs nach `cogs` verschoben
- bei allen Cogs den suffix Cog entfernt
- von Cogs genutzte Subklassen nach `cogs/components/<cog_name>` verschoben
- `data`-Verzeichnis erstellt um alle json-Dateien darin zusammenzufassen (json-dateien nicht gepusht)
- JSON-Dateien sinnvoll umbenannt  (z.B. `data.json -> module_information.json`, `courses.json` -> `learninggroup_headers.json`, ...)

Was mir bis jetzt nicht gefällt
- PollCog hatte eine Klasse Poll, durch das Entfernen des suffix Cog gab es Poll zweimal. Erstmal habe ich die Klasse Poll als ThePoll importiert bis wir was besseres haben
- Das import System von Python ist irritiert, wenn ein Verzeichnis und eine Datei selben Namens im gleichen Verzeichnis liegen. Daher habe ich noch das Verzeichnis `components` eingeführt. Ist für mich ok. Ohne hätte ich schöner gefunden.

**Comment by dnns01** [comment]
PR? :P

**Comment by L-MzK** [comment]
Nice! Mir war das immer länger werdende aufgefallen aber ich habe mich nicht getraut auch noch diese Baustelle zu öffnen.
Könnte der Emoji-Ordner in Images geschoben werden?

**Comment by dnns01** [comment]
> von Cogs genutzte Subklassen nach cogs/components/<cog_name> verschoben
Hm... mir fällt spontan jetzt kein top Vorschlag ein, aber irgendwie bin ich damit jetzt auch nur halb glücklich

> PollCog hatte eine Klasse Poll, durch das Entfernen des suffix Cog gab es Poll zweimal. Erstmal habe ich die Klasse Poll als ThePoll importiert bis wir was besseres haben
Vielleicht n Verzeichnis "dataclasses" oder so und da dann die alte `Poll` Klasse reinpacken? Also bei discord.py sind sowas wie die Messages ja auch auch dataclasses

> Das import System von Python ist irritiert, wenn ein Verzeichnis und eine Datei selben Namens im gleichen Verzeichnis liegen. Daher habe ich noch das Verzeichnis components eingeführt. Ist für mich ok. Ohne hätte ich schöner gefunden.
Wo liegt denn hier das Problem mit gleichem Namen von Verzeichnis und Datei?

**Comment by ffaadd** [comment]
> > PollCog hatte eine Klasse Poll, durch das Entfernen des suffix Cog gab es Poll zweimal. Erstmal habe ich die Klasse Poll als ThePoll importiert bis wir was besseres haben
> > Vielleicht n Verzeichnis "dataclasses" oder so und da dann die alte `Poll` Klasse reinpacken? Also bei discord.py sind sowas wie die Messages ja auch auch dataclasses

Siehe https://github.com/FU-Hagen-Discord/fernuni-bot/pull/46/files#r633583514

> 
> > Das import System von Python ist irritiert, wenn ein Verzeichnis und eine Datei selben Namens im gleichen Verzeichnis liegen. Daher habe ich noch das Verzeichnis components eingeführt. Ist für mich ok. Ohne hätte ich schöner gefunden.
> > Wo liegt denn hier das Problem mit gleichem Namen von Verzeichnis und Datei?

Wenn eine py-Datei und ein Verzeichnis gleichen Namens (Sagen wir `foo.py` und `foo`  in einem Verzeichnis sind und man 
`from foo.bar import Bar` ausführen möchte um aus der Datei `bar` im Verzeichnis `foo` die Klasse `Bar` zu importieren, wird stattdessen davon ausgegangen, dass die Datei `from foo.xyz` die Datei `foo.py` meint.
