### ISSUE TITLE
🗑️ als Löschmöglichkeit

### ISSUE THREAD

**Issue by McBotface** [FU-Hagen-Discord/fernuni-bot#49]

**Comment by L-MzK** [comment]
Verwandt mit #50
-> Soll die Möglichkeit geben, falls es doch eine Boty-Nachricht zu viel wird, sie löschen zu lassen.

**Comment by ffaadd** [comment]
Wer darf löschen? Jeder oder nur der Aufrufende? 
Wenn Jeder löschen darf etvtl. erst nach X Zeiteinheiten löschbar, damit einem die Info nicht direkt weggeworfen wird?

Diese Issue könnte sich erledigen wenn wir die Commandos so umbauen, dass sie per DM mit zusätzlichen Parametern aufgerufen werden können und dann auch dort geantwortet wird.

**Comment by Lou-M** [comment]
*Dem Issue #11 untergeordnet (das am Besten eher zu einem Projekt umgewandelt werden sollte)*

**Comment by dnns01** [comment]
Keine Ahnung wie du das mit dem Projekt genau meinst. Aber das können wir ab Donnerstag dann mal besprechen

**Comment by dnns01** [comment]
Mit Slash Commands kein Problem mehr. Nachrichten können dann als Ephemeral gesendet werden, um die Antwort nur an die Person zu schicken, die das Command ausgeführt hat
