### ISSUE TITLE
Ich fände es gut, wenn die meisten Antworten Botys nur an den Fragenden gingen. Die Antworten sind oft recht lang und füllen damit Channel mit Informationen, die in dem Moment meist nur den Fragenden interessieren. Eventuell wäre es sogar schön, wenn auch die Frage im Channel nicht sichtbar bliebe. Ich brauche zum Beispiel den Link zum Discord nicht alle paar Tage, bloß weil mal wieder ein Kommilitone danach fragte.

### ISSUE THREAD

**Issue by McBotface** [FU-Hagen-Discord/fernuni-bot#50]
*Vorschlag von JuliusD*

**Comment by ffaadd** [comment]
Der Grundgedanke war eigentlich, dass wenn jemand in einem Channel nach Mentoriaten/Welche Klausurform etc. fragt man ihm das kurz posten kann, daher geht das im Gegensatz zur Hilfe nicht an den User selbst. Da ich schon oft infos für andere Studierende rausgesucht habe finde ich die Variante des öffentlichen Postens besser.

**Comment by ffaadd** [comment]
Die Löschfunktion ist aus meiner Sicht ein guter Kompromiss. (Siehe weitere Kommentare in #49 )
Auch hier erstmal geschlossen, da durch andere Issue abgelöst.
