### ISSUE TITLE
Text-Commands umbauen

### ISSUE THREAD

**Issue by dnns01** [FU-Hagen-Discord/fernuni-bot#54]
* `!add-text-command` ersetzen durch `!command add` und als Command für alle freigeben. Wird das Command durch einen Mod ausgeführt, wird das entsprechende Command direkt erstellt. Nutzt ein Benutzer dieses Command, wird wie bei `!add-motivation` eine Nachricht in den Mod Channel gesendet, sodass ein Mod das freigeben muss
* `!text-commands` ersetzen durch `!command list` darf von jedem angesehen werden (würde ich vorschlagen)
* '!texts' ersetzen durch entweder `!command list <Command>` oder `!<Command> list`
* `!edit-text` ersetzen durch `!command edit`
* `!remove-text` ersetzen durch `!command remove` (Ggf mit Bestätigung um sicherzustellen, dass man den nicht versehentlich etwas falsches löscht)
* `!remove-text-command` kombinieren mit `!command remove` => Wird ein Index angegeben, dann wird der entsprechende Text gelöscht, wir kein Index angegeben, dann der gesamte Command
* `!add-motivation` kann dann wegfallen, weil stattdessen `!command add` benutzt werden kann

Für die entsprechenden "Help" Commands mal noch schauen, wie man die ggf. in das Schema einfügen kann.

**Comment by L-MzK** [comment]
Die Text-commands fand ich bis jetzt nicht so intuitiv also mag ich den Änderungsvorschlag.
Insbesondere die Verschmelzung zu `!command remove` wäre eine Steigerung der Eleganz.

Zu der allgemeinen Sichtbarkeit der `command list` bin ich zwiegespalten:
- einerseits freut es meine demokratiefreundliche Seite,
- andererseits kann man über den Weg keine Überraschungen mehr bereiten (ich habe gesehen, dass das 😆 Kommando gelöscht wurde 👀)

**Comment by L-MzK** [comment]
- [ ]  Bevor die Änderungen "live" gehen, sollten wir zumindest die Motivationsliste speichern, um sie erneut eingeben zu können.

**Comment by dnns01** [comment]
Wie meinst du speichern, um sie erneut eingeben zu können?

**Comment by L-MzK** [comment]
Wenn !add-motivation wegfällt und unter !command-add gefasst wird, muss man das Kommando und die Einträge neu erstellen, oder verstehe ich das falsch?

**Comment by dnns01** [comment]
Ne. Das ganze greift weiterhin auf den `!motivation` der JSON Datei zu. Das ist gar kein Problem
