### ISSUE TITLE
Aufruf von command help -> verwandte Kommandos ausgeben?

### ISSUE THREAD

**Issue by L-MzK** [FU-Hagen-Discord/fernuni-bot#56]
Wäre es möglich, über `!help <command>` zusätzlich eine Liste der Kommandos der selben Kategorie zu erhalten?

Bsp: `!help links` -> Direknachricht von Boty
> **links**
> Zeigt die Links an, die in diesem Channel (evtl. unter Berücksichtigung einer Gruppe) hinterlegt sind.
> 
> **Syntax**:
> ` !links <group?>`
> **Parameter**:
> `group `- (optional) Schränkt die angezeigten Links auf die übergebene Gruppe ein.

Hier könnte man einfügen:
> **In der selben Kategorie:** 
> `!add-link <group> <link> <title...>` - Fügt einen Link zum Channel hinzu.

***
Vollständige Kategorie (Auszug von `!help`):
> **Links**
> Feature zum Verwalten von Links innerhalb eines Channels.
> 
> `!add-link <group> <link> <title...>`
> Fügt einen Link zum Channel hinzu.
> 
> `!links <group?>`
> Zeigt die Links an, die in diesem Channel (evtl. unter Berücksichtigung einer Gruppe) hinterlegt sind.

**Comment by dnns01** [comment]
Wäre sicherlich möglich. Würde ich aber mal hinter die Umstrukturierung anstellen, die @ffaadd ja auch schon mal vorgeschlagen hat. Ich denke dann zeigt sich am ehesten, was man wie vorschlagen kann.

**Comment by L-MzK** [comment]
Würde es syntaktisch Sinn ergeben, (und funktionieren) Subcommands (wie `!poll suggest`) in der Hilfe des Elterncommands als parameter anzuführen? 

Beispielhafte Umsetzung bei `!poll`:
```Python
syntax = "!poll <subcommand?> <question> <answers...>",
brief = [...],
parameters={
    "subcommand": "(optionell) `!poll suggest` erstellt keine Umfrage, sondern schlägt eine Umfrage für den Umfrage-Kanal vor."
    "question": "Die Frage, die gestellt werden soll (in Anführungszeichen).",
    "answers...": "Durch Leerzeichen getrennte Antwortmöglichkeiten (die einzelnen Antworten in Anführungszeichen einschließen)."
}
```

Original: ab Zeile 17 im [Polls Cog](https://github.com/FU-Hagen-Discord/fernuni-bot/blob/master/cogs/polls.py).

**Comment by ffaadd** [comment]
Ich glaube das ist erledigt. Verwandte Kommandos sollten in einer Kommandogruppe sein. Dafür sollten wir nicht die Hilfe anpassen, sondern die Kommandos zu gruppen zusammenfassen. Gruppierte Kommandos werden von der Hilfe-Funktion beim Hauptkommando ausgegeben. Falls ich da was fehlinterpretiert habe, gerne wieder öffnen.
