### ISSUE TITLE
Stille-Treppe auch beim rejoin vergeben

### ISSUE THREAD

**Issue by ffaadd** [FU-Hagen-Discord/fernuni-bot#60]
Das Calmdown Modul soll beim Server-Join prüfen ob der joinende user bereits auf der Stillen Treppe sitzt und die Rolle erneut vergeben.

**Comment by dnns01** [comment]
https://discordpy.readthedocs.io/en/stable/api.html?highlight=member_update#discord.on_member_update
und 
https://discordpy.readthedocs.io/en/stable/api.html?highlight=member_update#discord.Member.pending

Bei on_member_update Event und dann prüfen, ob `before.pending == False` ist und `after.pending == True`.
Hintergrund: Wir haben inzwischen die Regelbestätigung angeschaltet, über diese Memberverification. Hast du da die Regeln nicht bestätigt, dann bist du automatisch auf der stillen Treppe. Vergibst du jemandem aber eine Rolle, dann nimmt Discord die Memberverification automatisch vor, ohne das die Person die Regeln bestätigen muss.

**Comment by dnns01** [comment]
Nicht mehr benötigt. Ähnliche Funktion inzwischen in Discord eingebaut!
