### ISSUE TITLE
Request-group -> Reihenfolge <semester> vor <open|closed> auch zulassen

### ISSUE THREAD

**Issue by Lou-M** [FU-Hagen-Discord/fernuni-bot#63]
_Edit: Erklärung für das Problem der Studentin wurde gefunden._
~~Eine Studentin hat mehrmals probiert, eine 1141 Gruppe anzufragen.
Von Boty kam nur `Fehler! Bitte gib an ob die Gruppe **offen** (**open**) oder **geschlossen** (**closed**) ist. Gib `!help request-group` für Details ein. `, 
obwohl sie der vorgegebenen Struktur gefolgt ist (`request-group <KURSNUMMER> <NAME-OHNE-LEERZEICHEN> <open|closed> <(wise|sose)YY`).~~

~~Auch als Mod hat die Anfrage nicht geklappt. Selbe Fehlermeldung.~~

**Comment by L-MzK** [comment]
Doch kein Bug.

> obwohl sie der vorgegebenen Struktur gefolgt ist (`request-group <KURSNUMMER> <NAME-OHNE-LEERZEICHEN> <open|closed> <(wise|sose)YY`).

Die Struktur die ich gefunden hatte war veraltet: eig. kommt` <open|closed>` tatsächlich **nach** `<(wise|sose)YY` und beim einen Versuch der Studentin, das auszutauschen, hat sich ein Leerzeichen in der Semesterangabe eingeschlichen. (Das ich in meinem Versuch als Mod auszuführen direkt mit kopiert habe 😐)

Das einzige was ich noch als ausbaufähig sehe ist:
-> Help verrät nicht, dass man die Ownership gleich mit angeben kann, könnte man hinzufügen.

**Comment by L-MzK** [comment]
Ok my bad, ich habe mit dem (mod-only) `!add-group` Kommando verwechselt, bei `request-group` gibt es kein <owner> Parameter und dadurch kein Anpassungsbedarf der Hilfe.

Einziges übriggebliebenes Verbesserungsvorschlag (von @ffaadd) : 
Boty beibringen, die Reihenfolge <semester> <open|closed> auch zu verstehen.

**Comment by dnns01** [comment]
@ffaadd 
Durch Verwendung von Slash Commands statt `!lg` sollte sich das Problem eigentlich recht leicht lösen lassen. Da ist die Reihenfolge nicht unbedingt entscheidend, vor allem bekommt man aber auch direkt angezeigt, welcher Parameter gerade gefragt ist.
Außerdem dürfte die Ausgabe der Lerngruppem im Lerngruppen Channel gerne nach Semester sortiert sein.
