### ISSUE TITLE
Bestätigung bei Terminen in der Vergangenheit

### ISSUE THREAD

**Issue by Lou-M** [FU-Hagen-Discord/fernuni-bot#68]
Boty könnte bei Erstellung anmerken oder bestätigen lassen, wenn ein Terminzeitpunkt sich in der Vergangenheit befindet.

**Comment by dnns01** [comment]
Erstellung von Terminen in der Vergangenheit wird grundsätzlich nicht mehr erlaubt. Sehe eigentlich keinen Grund dafür.
