### ISSUE TITLE
Timer-Funktion für Gruppenprojekte/ Lerngemeinschaften.

### ISSUE THREAD

**Issue by McBotface** [FU-Hagen-Discord/fernuni-bot#77]
Zwei Möglichkeiten, die sich nicht ausschließen müssen:
1. Rein textbasiert in einem Text-Channel auf der Vorlage der Appointments
2. Mit Ton in einem Voice-Channel.

Vorteile/ Nachteile:
1. Variante
[+] einfacher umzusetzen weil es die Vorlage gibt.
[-] der Server ist zu groß, dass man Puch-Benachrichtigungen bekommt. Man müsste beim Lernen/ wasauchimmer immer ein Auge auf dem Discord-Icon haben, ob man gerade angepingt wurde oder nicht.

2. Variante
[+] Minus der ersten Variante wird umgegangen. 
Kann man personalisieren mit Open Source Klingeltöne / Vogelgezwitscher, was auch immer :bird:
[-] Neuland für Boty der bisher nicht Voice-ausgerichtet ist: aufwendiger zu entwickeln.

**Comment by ffaadd** [comment]
Anregung von Sina: Timer soll auch außerhalb des Sprachchats abrufbar sein, damit man weiß wan pause ist und nicht reinplatzt.
