### ISSUE TITLE
xkcd-Link zur Webseite, statt zum Bild selbst

### ISSUE THREAD

**Issue by Lou-M** [FU-Hagen-Discord/fernuni-bot#80]
Bis jetzt liefert `!xkcd` den Comic + Comicbeschreibung. 
Der Titel des Embeds hat den Format "**xkcd #<comicnummer>**" und ist ein Link zum **Bild** des Comics.
_Bsp eines solchen Links: https://imgs.xkcd.com/comics/compass_and_straightedge.png_

Stattdessen würde ich vorschlagen, dass der Link zu `xkcd.com/<comicnummer>` führt.

(mit dem Segen der Urheberin)

**Comment by dnns01** [comment]
```python
        # Comic embedden
        e = discord.Embed()
        e.set_image(url=img) 
        e.url = img # Hier wird die URL gesetzt, auf die man klicken kann. Hier müsste also die URL zur Webseite statt img gesetzt werden
        e.title = f'xkcd #{num}'
        e.add_field(name=title, value=text)
        e.set_footer(text='https://xkcd.com', icon_url='https://xkcd.com/s/0b7742.png')
``` 

Die URL für den Comic #1234 lautet https://xkcd.com/1234/

**Comment by dnns01** [comment]
@Lou-M Du wolltest das ja machen. Ist das noch aktuell?

**Comment by Lou-M** [comment]
Ja das möchte ich noch machen 😇

**Comment by dnns01** [comment]
Wurde bei #191 mit umgesetzt
