### ISSUE TITLE
Timer Buttons expliziter machen

### ISSUE THREAD

**Issue by L-MzK** [FU-Hagen-Discord/fernuni-bot#84]
Nachfrage kommt fast jedes Mal: was bedeuten die Symbole? -> Eineindeutigkeit ist nicht gegeben, dazu mehrere Vorschläge:

### A. Ersetzen durch "auf dem ersten Blick klarere" Symbole
* 👍  für das "Eintragen" durch 🖐️  / 🙋 ersetzen?
* 👎 für die "Abmeldung" durch 🚶 ersetzen?
-> Alternativ: ⏱️ oder ⏳ als Toggle stattdessen (aber immer noch fraglich, ob klar ist was es macht, wenn man nicht eingeweiht ist)

oder 

### B. Buttons beschriften
* Beenden
* Nächste Phase
* Neustarten
* Anmelden
* Abmelden

außerdem

### C. Buttons anders anordnen
Um eine "natürlichere" Reihenfolge zu haben:
Anmelden | Abmelden |  Nächste Phase | Neustarten | Beenden

## 2. Buttons im Embed erläutern
-> Timer würde dementsprechend größer werden.

**Comment by samari-k** [comment]
Ich find Reihenfolge ändern und Buttons im Embed kurz erklären ne gute Kombi
