### ISSUE TITLE
Möglichkeit(Performance) prüfen, Boty Messages pro Zeiteinheit für jeden User überwachen zu lassen und wenn Threshold überschritten -> Stille Treppe

### ISSUE THREAD

**Issue by McBotface** [FU-Hagen-Discord/fernuni-bot#87]
Möglichkeit(Performance) prüfen, Boty Messages pro Zeiteinheit für jeden User überwachen zu lassen und wenn Threshold überschritten -> Stille Treppe

**Comment by dnns01** [comment]
AutoMod bietet denke ich genug Möglichkeiten und Auto Timeout besser erst mal nicht
