### ISSUE TITLE
Willkommensnachricht randomisieren

### ISSUE THREAD

**Issue by Lou-M** [FU-Hagen-Discord/fernuni-bot#88]
Vorschlag von @Patochan 

**_Implementierung_**:
Siehe die Randomisierung der [Arminfunktion von Boty](https://github.com/FU-Hagen-Discord/fernuni-bot/blob/master/cogs/armin.py).

Next Level wäre: die Empfangsdirektnachricht daran anpassen, ob User:
- Neu auf Discord ist,
- bereits in einem der anderen Fakultätsdiscords Mitglied ist.

**Comment by dnns01** [comment]
Inzwischen umgesetzt
