### ISSUE TITLE
!archive fixen

### ISSUE THREAD

**Issue by dnns01** [FU-Hagen-Discord/fernuni-bot#89]
`!archive` entweder so umbauen, dass es für alle Channels funktioniert, oder filtern, dass nur Lerngruppen Channel damit archiviert werden können. Aktuell kann das dazu führen, dass zum einen die ersten beiden Zeichen abgeschnitten und durch "archive-" ersetzt werden, und zum anderen wird versucht den Channel aus der Liste der Lerngruppen zu löschen, was zu einer Exception führt.

**Comment by dnns01** [comment]
Ist das noch aktuell?

**Comment by Lou-M** [comment]
Ich weiß nicht, ob die Exception bei den Lerngruppen noch geworfen wird aber das löschen des Ersten Zeichen passiert noch. 
Prinzipiell finde ich es gut, dass man damit jeglichen Channel löschen kann.

Vielleicht könnte es checken, ob es sich um eine Lerngruppe handelt:
- Ja -> aus der Liste entfernen, erste 2 Zeichen löschen
- Nein -> nichts davon tun

Auf jeden Fall: ˋ#archiv-ˋ vorsetzen.

**Comment by ffaadd** [comment]
Sollte mit Zeile 253-256 in learninggroups.py behoben sein.
```
        group_config = self.groups["groups"].get(str(channel.id))
        if not group_config:
            await channel.send("Das ist kein Lerngruppenkanal.")
            return
```
